# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 11:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created record')),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200, null=True)),
                ('number_employee', models.IntegerField(default=0)),
                ('address1', models.CharField(max_length=200, null=True)),
                ('address2', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('post_code', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('billing_address1', models.CharField(max_length=200, null=True)),
                ('billing_address2', models.CharField(max_length=200, null=True)),
                ('billing_state', models.CharField(max_length=200, null=True)),
                ('billing_city', models.CharField(max_length=200, null=True)),
                ('billing_post_code', models.CharField(max_length=200, null=True)),
                ('billing_country', models.CharField(max_length=200, null=True)),
                ('posts', models.IntegerField(default=0)),
                ('users', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created record')),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200, null=True)),
                ('number_employee', models.IntegerField(default=0)),
                ('address1', models.CharField(max_length=200, null=True)),
                ('address2', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('post_code', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('billing_address1', models.CharField(max_length=200, null=True)),
                ('billing_address2', models.CharField(max_length=200, null=True)),
                ('billing_state', models.CharField(max_length=200, null=True)),
                ('billing_city', models.CharField(max_length=200, null=True)),
                ('billing_post_code', models.CharField(max_length=200, null=True)),
                ('billing_country', models.CharField(max_length=200, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created record')),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('avatar', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created record')),
                ('deleted', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Account')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Employer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created record')),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address1', models.CharField(max_length=200, null=True)),
                ('address2', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('post_code', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created record')),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('posts', models.IntegerField(default=0)),
                ('users', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('rules', models.TextField()),
                ('is_default', models.SmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employer',
            name='account',
            field=models.ManyToManyField(through='recruitment.EmployerAccount', to='recruitment.Account'),
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Membership'),
        ),
    ]
