# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_auto_20170418_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(max_length=200)),
                ('config_label', models.CharField(max_length=200, null=True)),
                ('config_value', models.TextField()),
                ('config_default', models.BooleanField(default=False)),
            ],
        ),
    ]
