# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_auto_20170421_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='job_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='job_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
