# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_auto_20170505_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='password',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
