# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_auto_20170505_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lnk_facebook',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='lnk_linkedin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='lnk_tumblr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='lnk_twitter',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
