# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_auto_20170509_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created record')),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('experience', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
