# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import recruitment.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_auto_20170526_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=b'statics/media/no-image.png', upload_to=recruitment.helpers.generate_uploadfile),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='image',
            field=models.ImageField(default=b'statics/media/no-image.png', upload_to=recruitment.helpers.generate_uploadfile),
        ),
    ]
