# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import recruitment.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0016_auto_20170529_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[(b'Active', b'Active'), (b'Inactive', b'Inactive')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='image',
            field=models.ImageField(default=b'no-image.png', upload_to=recruitment.helpers.generate_uploadfile),
        ),
    ]
