# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import recruitment.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0017_auto_20170529_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=b'no-image.png', upload_to=recruitment.helpers.generate_uploadfile),
        ),
    ]
