# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0018_auto_20170529_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='blog_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[(b'New', b'New'), (b'Hot', b'Hot'), (b'N/A', b'N/A')], max_length=200, null=True),
        ),
    ]
